// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneCNPJ.Data;

#nullable disable

namespace OneCNPJ.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106184952_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CnpjEstabelecimentoCnaeSecundario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnaeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnae_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnaeId");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("cnpj_estab_cnae_sec");
                });

            modelBuilder.Entity("OneCNPJ.Domain.CnpjSocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<long?>("CnpjEmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataEntradaSociedade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada_sociedade");

                    b.Property<string>("DocumentoSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento_socio");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<string>("NomeSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_socio");

                    b.Property<long>("QualificacaoSocioId")
                        .HasColumnType("bigint")
                        .HasColumnName("qualificacao_socio_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_socio");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmpresaId");

                    b.HasIndex("ImportacaoId");

                    b.HasIndex("QualificacaoSocioId");

                    b.ToTable("cnpj_socio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CapitalSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capital_social");

                    b.Property<string>("CnpjBasico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_basico");

                    b.Property<long?>("CnpjEmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("EnteFederativoResponsavel")
                        .HasColumnType("text")
                        .HasColumnName("ente_federativo_responsavel");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<long>("NaturezaJuridicaId")
                        .HasColumnType("bigint")
                        .HasColumnName("natureza_juridica_id");

                    b.Property<int>("Porte")
                        .HasColumnType("integer")
                        .HasColumnName("porte");

                    b.Property<long>("QualificacaoSocioId")
                        .HasColumnType("bigint")
                        .HasColumnName("qualificacao_socio_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmpresaId");

                    b.HasIndex("ImportacaoId");

                    b.HasIndex("NaturezaJuridicaId");

                    b.HasIndex("QualificacaoSocioId");

                    b.ToTable("cnpj_empresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<long>("CnaeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnae_id");

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<string>("CnpjDv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_dv");

                    b.Property<long>("CnpjEmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_empresa");

                    b.Property<string>("CnpjOrdem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_ordem");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataInicioAtividade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_atividade");

                    b.Property<DateTime?>("DataSituacaoCadastral")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_situacao_cadastral");

                    b.Property<string>("IdentificadorMatrizFilial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificador_matriz_filial");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<long>("MotivoSituacaoCadastralId")
                        .HasColumnType("bigint")
                        .HasColumnName("motivo_situacao_cadastral_id");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint")
                        .HasColumnName("municipio_id");

                    b.Property<string>("NomeCidadeExterior")
                        .HasColumnType("text")
                        .HasColumnName("nome_cidade_exterior");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<string>("SituacaoCadastral")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao_cadastral");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoLogradouro")
                        .HasColumnType("text")
                        .HasColumnName("tipo_logradouro");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("CnaeId");

                    b.HasIndex("CnpjEmpresaId");

                    b.HasIndex("ImportacaoId");

                    b.HasIndex("MotivoSituacaoCadastralId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PaisId");

                    b.ToTable("cnpj_estabelecimento");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjImportacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnpjEmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_referencia");

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim_em");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_em");

                    b.Property<long>("LinhasEmpresasFalhas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_empresas_falhas");

                    b.Property<long>("LinhasEmpresasImportadas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_empresas_importadas");

                    b.Property<long>("LinhasEmpresasTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_empresas_total");

                    b.Property<long>("LinhasEstabelecimentosFalhas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_estabelecimentos_falhas");

                    b.Property<long>("LinhasEstabelecimentosImportadas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_estabelecimentos_importadas");

                    b.Property<long>("LinhasEstabelecimentosTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_estabelecimentos_total");

                    b.Property<long>("LinhasSatelitesFalhas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_satelites_falhas");

                    b.Property<long>("LinhasSatelitesImportadas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_satelites_importadas");

                    b.Property<long>("LinhasSimplesFalhas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_simples_falhas");

                    b.Property<long>("LinhasSimplesImportadas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_simples_importadas");

                    b.Property<long>("LinhasSimplesTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_simples_total");

                    b.Property<long>("LinhasSociosFalhas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_socios_falhas");

                    b.Property<long>("LinhasSociosImportadas")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_socios_importadas");

                    b.Property<long>("LinhasSociosTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("linhas_socios_total");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusEmpresas")
                        .HasColumnType("integer")
                        .HasColumnName("status_empresas");

                    b.Property<int>("StatusEstabelecimentos")
                        .HasColumnType("integer")
                        .HasColumnName("status_estabelecimentos");

                    b.Property<int>("StatusSatelites")
                        .HasColumnType("integer")
                        .HasColumnName("status_satelites");

                    b.Property<int>("StatusSimples")
                        .HasColumnType("integer")
                        .HasColumnName("status_simples");

                    b.Property<int>("StatusSocios")
                        .HasColumnType("integer")
                        .HasColumnName("status_socios");

                    b.Property<string>("UrlOrigem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_origem");

                    b.Property<string>("VersaoOrigem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("versao_origem");

                    b.HasKey("Id");

                    b.ToTable("cnpj_importacao");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjSimples", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<long>("CnpjEmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_empresa");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataExclusaoMei")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao_mei");

                    b.Property<DateTime?>("DataExclusaoSimples")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao_simples");

                    b.Property<DateTime?>("DataOpcaoMei")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_opcao_mei");

                    b.Property<DateTime?>("DataOpcaoSimples")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_opcao_simples");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<bool>("OptanteMei")
                        .HasColumnType("boolean")
                        .HasColumnName("optante_mei");

                    b.Property<bool>("OptanteSimples")
                        .HasColumnType("boolean")
                        .HasColumnName("optante_simples");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmpresaId")
                        .IsUnique();

                    b.HasIndex("ImportacaoId");

                    b.ToTable("cnpj_simples");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Conteudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("ImportacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("importacao_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("cnpj_conteudo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Falha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("CampoDestino")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("campo_destino");

                    b.Property<long>("CnpjEmpresaId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("ColunaOrigem")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("coluna_origem");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<int>("Linha")
                        .HasColumnType("integer")
                        .HasColumnName("linha");

                    b.PrimitiveCollection<List<string>>("LinhaConteudo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("linha_conteudo");

                    b.PrimitiveCollection<List<string>>("Motivo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("motivo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("ValorRecebido")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmpresaId");

                    b.ToTable("falha");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Ignorado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CnpjEmpresaId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("Linha")
                        .HasColumnType("bigint")
                        .HasColumnName("linha");

                    b.PrimitiveCollection<List<string>>("Motivo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("motivo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmpresaId");

                    b.ToTable("ignorado");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Cnae", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("cnae");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Layout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<int>("FormatoCadfiEnum")
                        .HasColumnType("integer")
                        .HasColumnName("formato_cnpj");

                    b.Property<int>("LinhaCabecalho")
                        .HasColumnType("integer")
                        .HasColumnName("linha_cabecalho");

                    b.Property<int>("LinhaDados")
                        .HasColumnType("integer")
                        .HasColumnName("linha_dados");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("layout");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.LayoutCampo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AtributoClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atributo_classe");

                    b.Property<string>("AtributoClasseAmigavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("atributo_classe_amigavel");

                    b.Property<string>("Cabecalho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cabecalho");

                    b.Property<string>("CabecalhoOrdem")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("cabecalho_ordem");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("LayoutId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModelObrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("model_obrigatorio");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("layout_campo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.MotivoSituacaoCadastral", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("motivo_situacao_cadastral");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("municipio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.NaturezaJuridica", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("natureza_juridica");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Pais", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("pais");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("qualificacao_socio");
                });

            modelBuilder.Entity("CnpjEstabelecimentoCnaeSecundario", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Cnae", "Cnae")
                        .WithMany()
                        .HasForeignKey("CnaeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjEstabelecimento", "Estabelecimento")
                        .WithMany("CnaesSecundarios")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cnae");

                    b.Navigation("Estabelecimento");

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("OneCNPJ.Domain.CnpjSocio", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", null)
                        .WithMany("Socios")
                        .HasForeignKey("CnpjEmpresaId");

                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", "QualificacaoSocio")
                        .WithMany()
                        .HasForeignKey("QualificacaoSocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Importacao");

                    b.Navigation("QualificacaoSocio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", null)
                        .WithMany("CnpjEmpresa")
                        .HasForeignKey("CnpjEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.NaturezaJuridica", "NaturezaJuridica")
                        .WithMany()
                        .HasForeignKey("NaturezaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", "QualificacaoSocio")
                        .WithMany()
                        .HasForeignKey("QualificacaoSocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Importacao");

                    b.Navigation("NaturezaJuridica");

                    b.Navigation("QualificacaoSocio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Cnae", "Cnae")
                        .WithMany()
                        .HasForeignKey("CnaeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "CnpjEmpresa")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("CnpjEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.MotivoSituacaoCadastral", "MotivoSituacaoCadastral")
                        .WithMany()
                        .HasForeignKey("MotivoSituacaoCadastralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cnae");

                    b.Navigation("CnpjEmpresa");

                    b.Navigation("Importacao");

                    b.Navigation("MotivoSituacaoCadastral");

                    b.Navigation("Municipio");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjSimples", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "CnpjEmpresa")
                        .WithOne("Simples")
                        .HasForeignKey("OneCNPJ.Domain.Models.CnpjSimples", "CnpjEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnpjEmpresa");

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Conteudo", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjImportacao", "Importacao")
                        .WithMany()
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Falha", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "CnpjEmpresa")
                        .WithMany()
                        .HasForeignKey("CnpjEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CnpjEmpresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Ignorado", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "CnpjEmpresa")
                        .WithMany()
                        .HasForeignKey("CnpjEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CnpjEmpresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.LayoutCampo", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Layout", "Layout")
                        .WithMany("Campos")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.Navigation("Estabelecimentos");

                    b.Navigation("Simples");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.Navigation("CnaesSecundarios");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjImportacao", b =>
                {
                    b.Navigation("CnpjEmpresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Layout", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
