// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneCNPJ.Data;

#nullable disable

namespace OneCNPJ.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CnpjEstabelecimentoCnaeSecundario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnaeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnae_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnaeId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("cnpj_estab_cnae_sec");
                });

            modelBuilder.Entity("OneCNPJ.Domain.CnpjSocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataEntradaSociedade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada_sociedade");

                    b.Property<string>("DocumentoSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento_socio");

                    b.Property<string>("NomeSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_socio");

                    b.Property<long>("QualificacaoSocioId")
                        .HasColumnType("bigint")
                        .HasColumnName("qualificacao_socio_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoSocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_socio");

                    b.HasKey("Id");

                    b.HasIndex("CnpjBasico");

                    b.HasIndex("QualificacaoSocioId");

                    b.ToTable("cnpj_socio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CapitalSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capital_social");

                    b.Property<string>("CnpjBasico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_basico");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("EnteFederativoResponsavel")
                        .HasColumnType("text")
                        .HasColumnName("ente_federativo_responsavel");

                    b.Property<long>("NaturezaJuridicaId")
                        .HasColumnType("bigint")
                        .HasColumnName("natureza_juridica_id");

                    b.Property<int>("Porte")
                        .HasColumnType("integer")
                        .HasColumnName("porte");

                    b.Property<long>("QualificacaoResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("qualificacao_responsavel_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NaturezaJuridicaId");

                    b.HasIndex("QualificacaoResponsavelId");

                    b.ToTable("cnpj_empresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<long>("CnaePrincipalId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnae_principal_id");

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<string>("CnpjDv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_dv");

                    b.Property<string>("CnpjOrdem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_ordem");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataInicioAtividade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_atividade");

                    b.Property<DateTime?>("DataSituacaoCadastral")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_situacao_cadastral");

                    b.Property<string>("IdentificadorMatrizFilial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificador_matriz_filial");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<long>("MotivoSituacaoCadastralId")
                        .HasColumnType("bigint")
                        .HasColumnName("motivo_situacao_cadastral_id");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint")
                        .HasColumnName("municipio_id");

                    b.Property<string>("NomeCidadeExterior")
                        .HasColumnType("text")
                        .HasColumnName("nome_cidade_exterior");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<string>("SituacaoCadastral")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao_cadastral");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoLogradouro")
                        .HasColumnType("text")
                        .HasColumnName("tipo_logradouro");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("CnaePrincipalId");

                    b.HasIndex("CnpjBasico");

                    b.HasIndex("MotivoSituacaoCadastralId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PaisId");

                    b.ToTable("cnpj_estabelecimento");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjSimples", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CnpjBasico")
                        .HasColumnType("bigint")
                        .HasColumnName("cnpj_basico");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataExclusaoMei")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao_mei");

                    b.Property<DateTime?>("DataExclusaoSimples")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao_simples");

                    b.Property<DateTime?>("DataOpcaoMei")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_opcao_mei");

                    b.Property<DateTime?>("DataOpcaoSimples")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_opcao_simples");

                    b.Property<bool>("OptanteMei")
                        .HasColumnType("boolean")
                        .HasColumnName("optante_mei");

                    b.Property<bool>("OptanteSimples")
                        .HasColumnType("boolean")
                        .HasColumnName("optante_simples");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CnpjBasico")
                        .IsUnique();

                    b.ToTable("cnpj_simples");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Cnae", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("cnae");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.MotivoSituacaoCadastral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("motivo_situacao_cadastral");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("municipio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.NaturezaJuridica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("natureza_juridica");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("pais");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("qualificacao_socio");
                });

            modelBuilder.Entity("CnpjEstabelecimentoCnaeSecundario", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Cnae", "Cnae")
                        .WithMany()
                        .HasForeignKey("CnaeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjEstabelecimento", "Estabelecimento")
                        .WithMany("CnaesSecundarios")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cnae");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("OneCNPJ.Domain.CnpjSocio", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "Empresa")
                        .WithMany("Socios")
                        .HasForeignKey("CnpjBasico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", "QualificacaoSocio")
                        .WithMany()
                        .HasForeignKey("QualificacaoSocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("QualificacaoSocio");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.NaturezaJuridica", "NaturezaJuridica")
                        .WithMany()
                        .HasForeignKey("NaturezaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.QualificacaoSocio", "QualificacaoResponsavel")
                        .WithMany()
                        .HasForeignKey("QualificacaoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NaturezaJuridica");

                    b.Navigation("QualificacaoResponsavel");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Cnae", "CnaePrincipal")
                        .WithMany()
                        .HasForeignKey("CnaePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "Empresa")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("CnpjBasico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.MotivoSituacaoCadastral", "MotivoSituacaoCadastral")
                        .WithMany()
                        .HasForeignKey("MotivoSituacaoCadastralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CnaePrincipal");

                    b.Navigation("Empresa");

                    b.Navigation("MotivoSituacaoCadastral");

                    b.Navigation("Municipio");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjSimples", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.CnpjEmpresa", "Empresa")
                        .WithOne("Simples")
                        .HasForeignKey("OneCNPJ.Domain.Models.CnpjSimples", "CnpjBasico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEmpresa", b =>
                {
                    b.Navigation("Estabelecimentos");

                    b.Navigation("Simples");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.CnpjEstabelecimento", b =>
                {
                    b.Navigation("CnaesSecundarios");
                });
#pragma warning restore 612, 618
        }
    }
}
