// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneCNPJ.Data;

#nullable disable

namespace OneCNPJ.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneCNPJ.Domain.Models.Cadfi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hash");

                    b.PrimitiveCollection<List<int>>("LinhasComErrosNaoAdaptados175")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("linhas_com_erros_nao_adaptados_175");

                    b.PrimitiveCollection<List<int>>("LinhasComErrosRegistroClasse")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("linhas_com_erros_registro_classe");

                    b.PrimitiveCollection<List<int>>("LinhasComErrosRegistroFundo")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("linhas_com_erros_registro_fundo");

                    b.PrimitiveCollection<List<int>>("LinhasComErrosRegistroSubclasse")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("linhas_com_erros_registro_subclasse");

                    b.Property<int>("LinhasFalhasNaoAdaptados175")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_falhas_nao_adaptados_175");

                    b.Property<int>("LinhasFalhasRegistroClasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_falhas_registro_classe");

                    b.Property<int>("LinhasFalhasRegistroFundo")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_falhas_registro_fundo");

                    b.Property<int>("LinhasFalhasRegistroSubclasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_falhas_registro_subclasse");

                    b.Property<int>("LinhasIgnoradasNaoAdaptados175")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_ignoradas_nao_adaptados_175");

                    b.Property<int>("LinhasIgnoradasRegistroClasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_ignoradas_registro_classe");

                    b.Property<int>("LinhasIgnoradasRegistroFundo")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_ignoradas_registro_fundo");

                    b.Property<int>("LinhasIgnoradasRegistroSubclasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_ignoradas_registro_subclasse");

                    b.Property<int>("LinhasImportadasNaoAdaptados175")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_importadas_nao_adaptados_175");

                    b.Property<int>("LinhasImportadasRegistroClasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_importadas_registro_classe");

                    b.Property<int>("LinhasImportadasRegistroFundo")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_importadas_registro_fundo");

                    b.Property<int>("LinhasImportadasRegistroSubclasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_importadas_registro_subclasse");

                    b.Property<int>("LinhasNaoAdaptados175")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_nao_adaptados_175");

                    b.Property<int>("LinhasRegistroClasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_registro_classe");

                    b.Property<int>("LinhasRegistroFundo")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_registro_fundo");

                    b.Property<int>("LinhasRegistroSubclasse")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_registro_subclasse");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusNaoAdaptados175")
                        .HasColumnType("integer")
                        .HasColumnName("status_nao_adaptados_175");

                    b.Property<int>("StatusRegistroClasse")
                        .HasColumnType("integer")
                        .HasColumnName("status_registro_classe");

                    b.Property<int>("StatusRegistroFundo")
                        .HasColumnType("integer")
                        .HasColumnName("status_registro_fundo");

                    b.Property<int>("StatusRegistroSubclasse")
                        .HasColumnType("integer")
                        .HasColumnName("status_registro_subclasse");

                    b.HasKey("Id");

                    b.ToTable("cadfi");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Conteudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Administrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("admin");

                    b.Property<string>("AplicarTotalExterior")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("invest_cempr_exter");

                    b.Property<DateOnly?>("AtividadeDataInicial")
                        .HasColumnType("date")
                        .HasColumnName("dt_ini_ativ");

                    b.Property<string>("Auditor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auditor");

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.Property<string>("Classe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classe");

                    b.Property<string>("ClasseAnbima")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classe_anbima");

                    b.Property<DateOnly?>("ClasseDataInicial")
                        .HasColumnType("date")
                        .HasColumnName("dt_ini_classe");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_fundo");

                    b.Property<string>("CnpjAdministrador")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_admin");

                    b.Property<string>("CnpjAuditor")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_auditor");

                    b.Property<string>("CnpjControlador")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_controlador");

                    b.Property<string>("CnpjCustodiante")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_custodiante");

                    b.Property<string>("CodigoCvm")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cd_cvm");

                    b.Property<string>("Condominio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("condom");

                    b.Property<string>("Controlador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controlador");

                    b.Property<string>("Cotas")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("fundo_cotas");

                    b.Property<string>("Custodiante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custodiante");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateOnly?>("DataCancelamento")
                        .HasColumnType("date")
                        .HasColumnName("dt_cancel");

                    b.Property<DateOnly?>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("const");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("dt_reg");

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("denom_social");

                    b.Property<string>("Diretor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("diretor");

                    b.Property<string>("DocumentoGestor")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cpf_cnpj_gestor");

                    b.Property<string>("EntidadeInvestimento")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("entid_invest");

                    b.Property<string>("Exclusivo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("fundo_exclusivo");

                    b.Property<DateOnly?>("ExercicioDataFinal")
                        .HasColumnType("date")
                        .HasColumnName("dt_fim_exerc");

                    b.Property<DateOnly?>("ExercicioDataInicial")
                        .HasColumnType("date")
                        .HasColumnName("dt_ini_exerc");

                    b.Property<string>("Gestor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gestor");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasPrecision(26, 2)
                        .HasColumnType("numeric(26,2)")
                        .HasColumnName("vl_patrim_liq");

                    b.Property<DateOnly?>("PatrimonioLiquidoData")
                        .HasColumnType("date")
                        .HasColumnName("dt_patrim_liq");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("publico_alvo");

                    b.Property<string>("Rentabilidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rentab_fundo");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sit");

                    b.Property<DateOnly?>("SituacaoDataInicial")
                        .HasColumnType("date")
                        .HasColumnName("dt_ini_sit");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaAdministracao")
                        .HasPrecision(26, 8)
                        .HasColumnType("numeric(26,8)")
                        .HasColumnName("taxa_adm");

                    b.Property<string>("TaxaAdministracaoInfo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("inf_taxa_adm");

                    b.Property<decimal>("TaxaPerformance")
                        .HasPrecision(26, 2)
                        .HasColumnType("numeric(26,2)")
                        .HasColumnName("taxa_perfm");

                    b.Property<string>("TaxaPerformanceInfo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("inf_taxa_perfm");

                    b.Property<string>("TipoFundo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tp_fundo");

                    b.Property<string>("TipoGestor")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pf_pj_gestor");

                    b.Property<string>("TributacaoLongoPrazo")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("trib_lprazo");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.ToTable("conteudo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Falha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("CampoDestino")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("campo_destino");

                    b.PrimitiveCollection<List<string>>("ColunaOrigem")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("coluna_origem");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<int>("Linha")
                        .HasColumnType("integer")
                        .HasColumnName("linha");

                    b.PrimitiveCollection<List<string>>("LinhaConteudo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("linha_conteudo");

                    b.PrimitiveCollection<List<string>>("Motivo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("motivo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("ValorRecebido")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.ToTable("falha");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Ignorado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("Linha")
                        .HasColumnType("bigint")
                        .HasColumnName("linha");

                    b.PrimitiveCollection<List<string>>("Motivo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("motivo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.ToTable("ignorado");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroClasse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Auditor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auditor");

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClasseAnbima")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classe_anbima");

                    b.Property<string>("ClasseCotas")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("classe_cotas");

                    b.Property<string>("ClasseEsg")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("classe_esg");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classificacao");

                    b.Property<string>("CnpjAuditor")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_auditor");

                    b.Property<string>("CnpjClasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj_classe");

                    b.Property<string>("CnpjControlador")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_controlador");

                    b.Property<string>("CnpjCustodiante")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_custodiante");

                    b.Property<string>("CodigoCvm")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_cvm");

                    b.Property<string>("Controlador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controlador");

                    b.Property<string>("Custodiante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custodiante");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateOnly?>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataInicioSituacao")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_situacao");

                    b.Property<DateOnly?>("DataPatrimonioLiquido")
                        .HasColumnType("date")
                        .HasColumnName("data_patrimonio_liquido");

                    b.Property<DateOnly?>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("denominacao_social");

                    b.Property<string>("EntidadeInvestimento")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("entidade_investimento");

                    b.Property<string>("Exclusivo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("exclusivo");

                    b.Property<string>("FormaCondominio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forma_condominio");

                    b.Property<long>("IdRegistroClasse")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_classe");

                    b.Property<long>("IdRegistroFundo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_fundo");

                    b.Property<string>("IndicadorDesempenho")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("indicador_desempenho");

                    b.Property<decimal?>("PatrimonioLiquido")
                        .HasColumnType("decimal(28,2)")
                        .HasColumnName("patrimonio_liquido");

                    b.Property<string>("PermitidoAplicacaoCemPorCentoExterior")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("permitido_aplicacao_cem_por_cento_exterior");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("publico_alvo");

                    b.Property<long?>("RegistroFundoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoClasse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_classe");

                    b.Property<string>("TributacaoLongoPrazo")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tributacao_longo_prazo");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.HasIndex("RegistroFundoId");

                    b.ToTable("registro_classe");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroFundo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Administrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrador");

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.Property<string>("CnpjAdministrador")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_administrador");

                    b.Property<string>("CnpjFundo")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_fundo");

                    b.Property<string>("CodigoCvm")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_cvm");

                    b.Property<DateOnly?>("DataAdaptacaoRcvm175")
                        .HasColumnType("date")
                        .HasColumnName("data_adaptacao_rcvm_175");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateOnly?>("DataCancelamento")
                        .HasColumnType("date")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateOnly?>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituição");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataFimExercicioSocial")
                        .HasColumnType("date")
                        .HasColumnName("data_fim_exercicio_social");

                    b.Property<DateOnly?>("DataInicioExercicioSocial")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_exercicio_social");

                    b.Property<DateOnly?>("DataInicioSituacao")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_situacao");

                    b.Property<DateOnly?>("DataPatrimonioLiquido")
                        .HasColumnType("date")
                        .HasColumnName("data_patrimonio_liquido");

                    b.Property<DateOnly?>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("denominacao_social");

                    b.Property<string>("Diretor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("diretor");

                    b.Property<string>("DocumentoGestor")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("documento_gestor");

                    b.Property<string>("Gestor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gestor");

                    b.Property<long>("IdRegistroFundo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_fundo");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasPrecision(26, 2)
                        .HasColumnType("numeric(26,2)")
                        .HasColumnName("patrimonio_liquido");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoFundo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_fundo");

                    b.Property<string>("TipoPessoaGestor")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_pessoa_gestor");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.ToTable("registro_fundo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroSubclasse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Cabecalho")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cabecalho");

                    b.Property<long>("CadfiId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoCvm")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_cvm");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateOnly?>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataInicioSituacao")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_situacao");

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("denominacao_social");

                    b.Property<string>("Exclusivo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("exclusivo");

                    b.Property<string>("FormaCondominio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forma_condominio");

                    b.Property<long>("IdRegistroClasse")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_classe");

                    b.Property<long>("IdRegistroSubclasse")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_subclasse");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("publico_alvo");

                    b.Property<long?>("RegistroClasseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CadfiId");

                    b.HasIndex("RegistroClasseId");

                    b.ToTable("registro_subclasse");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Layout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<int>("FormatoCadfiEnum")
                        .HasColumnType("integer")
                        .HasColumnName("formato_cadfi");

                    b.Property<int>("LinhaCabecalho")
                        .HasColumnType("integer")
                        .HasColumnName("linha_cabecalho");

                    b.Property<int>("LinhaDados")
                        .HasColumnType("integer")
                        .HasColumnName("linha_dados");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("layout");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.LayoutCampo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AtributoClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atributo_classe");

                    b.Property<string>("AtributoClasseAmigavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("atributo_classe_amigavel");

                    b.Property<string>("Cabecalho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cabecalho");

                    b.Property<string>("CabecalhoOrdem")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("cabecalho_ordem");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("LayoutId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModelObrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("model_obrigatorio");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("layout_campo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Conteudo", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadfi");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Falha", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadfi");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Ignorado", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadfi");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroClasse", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.RegistroFundo", "RegistroFundo")
                        .WithMany()
                        .HasForeignKey("RegistroFundoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cadfi");

                    b.Navigation("RegistroFundo");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroFundo", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadfi");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.RegistroSubclasse", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Cadfi", "Cadfi")
                        .WithMany()
                        .HasForeignKey("CadfiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneCNPJ.Domain.Models.RegistroClasse", "RegistroClasse")
                        .WithMany()
                        .HasForeignKey("RegistroClasseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cadfi");

                    b.Navigation("RegistroClasse");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.LayoutCampo", b =>
                {
                    b.HasOne("OneCNPJ.Domain.Models.Satelites.Layout", "Layout")
                        .WithMany("Campos")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("OneCNPJ.Domain.Models.Satelites.Layout", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
